blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/hirotomoyamada/yamada-ui/discussions
    about: Ask questions and discuss topics with other community members
