name: Release

on: [workflow_dispatch]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Update Changelog
        run: pnpm gen:changelog
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update Theme
        run: pnpm gen:theme
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update Props
        run: pnpm gen:props
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Update Search content
        run: pnpm gen:search

      - name: Update Yamada UI
        run: pnpm up '@yamada-ui/*' --latest

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: main
          delete-branch: true
          commit-message: "ci(changesets): version packages"
          title: "Version Packages"
          branch: changeset-release/main
          assignees: "hirotomoyamada"
