name: Observe Issues

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Update issues
        run: pnpm observe:issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_HELP_WANTED_WEBHOOK_URL: ${{ secrets.DISCORD_HELP_WANTED_WEBHOOK_URL }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Create or update issues
        run: pnpm test:issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODECOV_API_TOKEN: ${{ secrets.CODECOV_API_TOKEN }}
