name: Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Sync Files
        uses: Redocly/repo-file-sync-action@master
        with:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
          GIT_EMAIL: hirotomo.yamada@avap.co.jp
          GIT_USERNAME: hirotomoyamada

      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: hirotomoyamada/yamada-docs
          ref: repo-sync/yamada-ui/default
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm build:changelogs

      - name: Commit changelogs
        run: |
          git add .
          git commit -m 'ci(changelog): version packages'
          git push
