name: Test

on:
  workflow_dispatch:
    inputs:
      chromium:
        description: "Chromium"
        required: false
        default: true
        type: boolean
      firefox:
        description: "Firefox"
        required: false
        default: false
        type: boolean
      webkit:
        description: "Webkit"
        required: false
        default: false
        type: boolean
  workflow_call:

jobs:
  browser:
    name: ${{ matrix.name }}
    env:
      run_browser: ${{ github.event_name != 'workflow_dispatch' || (matrix.id == 'chromium' && inputs.chromium) || (matrix.id == 'firefox' && inputs.firefox) || (matrix.id == 'webkit' && inputs.webkit) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: chromium
            name: Chromium
            coverage: "true"
          - id: firefox
            name: Firefox
            coverage: "false"
          - id: webkit
            name: Webkit
            coverage: "false"
    steps:
      - name: Checkout
        if: env.run_browser == 'true'
        uses: actions/checkout@v4

      - name: Check modified files
        id: check-modified
        if: env.run_browser == 'true'
        uses: tj-actions/changed-files@v46
        with:
          files: |
            packages/**/(package.json|vitest.config.ts)
            packages/**/(src|test)/**/*.{ts,tsx}
            !packages/**/src/**/*.stories.{ts,tsx}
            !packages/workspace/src/**
            packages/workspace/src/vitest/**

      - name: Set run flag
        if: env.run_browser == 'true'
        run: echo "RUN_TESTS=${{ github.event_name == 'workflow_dispatch' || steps.check-modified.outputs.any_changed == 'true' }}" >> "$GITHUB_ENV"

      - name: Install
        if: env.run_browser == 'true' && env.RUN_TESTS == 'true'
        uses: ./.github/composite-actions/install

      - name: Setup Browser
        if: env.run_browser == 'true' && env.RUN_TESTS == 'true'
        working-directory: packages/react
        run: pnpm playwright install ${{ matrix.id }} --with-deps

      - name: Run tests
        if: env.run_browser == 'true' && env.RUN_TESTS == 'true' && matrix.coverage == 'true'
        run: pnpm test:coverage

      - name: Run Browser Test on ${{ matrix.name }}
        if: env.run_browser == 'true' && env.RUN_TESTS == 'true' && matrix.coverage != 'true'
        working-directory: packages/react
        run: pnpm test:${{ matrix.id }}

      - name: Upload coverage
        if: env.run_browser == 'true' && env.RUN_TESTS == 'true' && matrix.coverage == 'true'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          file: ./packages/react/coverage/coverage-final.json,./packages/utils/coverage/coverage-final.json
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          codecov_yml_path: ./codecov.yml
