name: Test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      TURBO_TOKEN:
        required: false
      CODECOV_TOKEN:
        required: false

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  browser:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - id: chromium
            name: Chromium
            coverage: "true"
          - id: firefox
            name: Firefox
            coverage: "false"
          - id: webkit
            name: Webkit
            coverage: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check modified files
        id: check-modified
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: |
            turbo.json
            packages/**/(package.json|vitest.config.ts)
            packages/**/(src|test)/**/*.{ts,tsx}
            !packages/**/src/**/*.stories.{ts,tsx}
            !packages/workspace/src/**
            packages/workspace/src/vitest/**
            .github/workflows/test.yml
            .github/workflows/quality.yml

      - name: Restore turbo cache
        if: steps.check-modified.outputs.any_changed == 'true'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.id }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.job }}-${{ matrix.id }}-
            ${{ runner.os }}-turbo-${{ github.job }}-

      - name: Install
        if: steps.check-modified.outputs.any_changed == 'true'
        uses: ./.github/composite-actions/install

      - name: Setup Browser
        if: steps.check-modified.outputs.any_changed == 'true'
        working-directory: packages/react
        run: pnpm playwright install ${{ matrix.id }} --with-deps

      - name: Run tests
        if: steps.check-modified.outputs.any_changed == 'true' && matrix.coverage == 'true'
        run: pnpm test:coverage

      - name: Run Browser Test on ${{ matrix.name }}
        if: steps.check-modified.outputs.any_changed == 'true' && matrix.coverage != 'true'
        run: pnpm test:${{ matrix.id }}

      - name: Upload coverage
        if: steps.check-modified.outputs.any_changed == 'true' && matrix.coverage == 'true'
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          fail_ci_if_error: false
          file: ./packages/react/coverage/coverage-final.json,./packages/utils/coverage/coverage-final.json
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          codecov_yml_path: ./codecov.yml
